apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server2
  template:
    metadata:
      labels:
        app: echo-server2
    spec:
      containers:
      - name: echo-server2-container
        image: echo-server2:latest # Use the image you built
        imagePullPolicy: Never
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: echo-server2-service
spec:
  type: LoadBalancer
  selector:
    app: echo-server2
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4000
      nodePort: 32009 # This is the NodePort for external access
  