apiVersion: v1
kind: ConfigMap
metadata:
  name: echo-server-config
data:
  customMessage: "Hello from ConfigMap!"
  secondMessage: "Hello from second Config Message!"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
      - name: echo-server-container
        image: echo-server:latest # Use the image you built
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: CUSTOM_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: echo-server-config
              key: customMessage
        volumeMounts:
          - name: foo
            mountPath: "/etc/foo"
            readOnly: true
      volumes:
        - name: foo
          configMap:
            name: echo-server-config


            
---
apiVersion: v1
kind: Service
metadata:
  name: echo-server-service
spec:
  type: NodePort
  selector:
    app: echo-server
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000
      nodePort: 32000 # This is the NodePort for external access
